-- SYSTEM in System_Progetto
CREATE TABLESPACE DATI_PROGETTO_TS DATAFILE
'C:\File_progetto\DATI_PROGETTO_TS.dbf' SIZE 150 M;

CREATE TABLESPACE FOTO_PROGETTO_TS DATAFILE
'C:\File_progetto\FOTO_PROGETTO_TS.dbf' SIZE 1 G;

CREATE TABLESPACE GIUDIZI_PROGETTO_TS DATAFILE
'C:\File_progetto\GIUDIZI_PROGETTO_TS.dbf' SIZE 10 M;

CREATE USER DBA_PROGETTO DEFAULT TABLESPACE DATI_PROGETTO_TS IDENTIFIED BY 202208;
GRANT DBA, UNLIMITED TABLESPACE TO DBA_PROGETTO;