-- DBA_PROGETTO in Dba_Progetto
-- CREAZIONE RUOLI
CREATE ROLE RUOLO_AUTISTA;

GRANT CONNECT TO RUOLO_AUTISTA;
GRANT RESOURCE ON AUTO TO RUOLO_AUTISTA;
GRANT RESOURCE ON VIAGGI TO RUOLO_AUTISTA;      -- in alternativa: INSERT, UPDATE, DELETE
GRANT RESOURCE ON RECENSIONI TO RUOLO_AUTISTA;
GRANT UPDATE ON PRENOTAZIONI TO RUOLO_AUTISTA;
GRANT SELECT PRENOTAZIONI TO RUOLO_AUTISTA;

CREATE USER AUTISTA IDENTIFIED BY 0820;
GRANT RUOLO_AUTISTA TO AUTISTA;

CREATE ROLE RUOLO_PASSEGGERO;

GRANT CONNECT TO RUOLO_PASSEGGERO;
GRANT INSERT, DELETE ON PRENOTAZIONI TO RUOLO_PASSEGGERO;
GRANT RESOURCE ON RECENSIONI TO RUOLO_PASSEGGERO;

CREATE USER PASSEGGERO IDENTIFIED BY 0822;
GRANT RUOLO_PASSEGGERO TO PASSEGGERO;