-- DBA_PROGETTO in Dba_Progetto
-- CREAZIONE RELAZIONI
CREATE TABLE UTENTI (
	ID NUMBER(6),
	USERNAME VARCHAR2(20) NOT NULL UNIQUE,
	PASSWORD VARCHAR2(20) NOT NULL,
	NOME VARCHAR2(50) NOT NULL,
	COGNOME VARCHAR2(50) NOT NULL,
	DATA_NASCITA DATE,
	SESSO CHAR(1) CHECK (SESSO = 'M' OR SESSO = 'F'),
	DOCUMENTO CHAR(9) UNIQUE,		
	FOTO BLOB,				
	CELLULARE NUMBER(10) NOT NULL,
	EMAIL VARCHAR2(100) NOT NULL,
	CONSTRAINT PK_UTENTI PRIMARY KEY (ID)
)
STORAGE (INITIAL 2730 K);

CREATE TABLE AUTISTI (
	UTENTE NUMBER(6),
	NUMERO_PATENTE CHAR(10) NOT NULL UNIQUE,	
	SCADENZA_PATENTE DATE NOT NULL,
	AUTO CHAR(7) NOT NULL,
	CONSTRAINT PK_AUTISTI PRIMARY KEY (UTENTE)
)
STORAGE (INITIAL 58 K);

CREATE TABLE PASSEGGERI (
	UTENTE NUMBER(6),
	CONSTRAINT PK_PASSEGGERI PRIMARY KEY (UTENTE)
)
STORAGE (INITIAL 40 K);

CREATE TABLE AUTO (
	TARGA CHAR(7),
	MODELLO VARCHAR2(50),
	COLORE VARCHAR2(30),
	SCADENZA_ASSICURAZIONE DATE NOT NULL,
	CONSTRAINT PK_AUTO PRIMARY KEY (TARGA)
)
STORAGE (INITIAL 188 K);

CREATE TABLE RECENSIONI (
	CODICE NUMBER(6),
	VOTO NUMBER(1) CHECK (VOTO > 0 AND VOTO < 6),
	GIUDIZIO CLOB,
	RECENSENTE NUMBER(6) NOT NULL,
	RECENSITO NUMBER(6) NOT NULL,
	VIAGGIO NUMBER(6) NOT NULL,
	CONSTRAINT PK_RECENSIONI PRIMARY KEY (CODICE)
)
STORAGE (INITIAL 13250 K);

CREATE TABLE PRENOTAZIONI (
	CODICE NUMBER(6),
	PASSEGGERO NUMBER(6) NOT NULL,
	VIAGGIO NUMBER(6) NOT NULL,
	STATO VARCHAR2(20) CHECK (STATO = 'Accettata' or STATO = 'Rifiutata'),
	CONSTRAINT PK_PRENOTAZIONI PRIMARY KEY (CODICE)
)
STORAGE (INITIAL 17500 K);

-- NON CREATE PER GPS
CREATE TABLE VIAGGI (
	CODICE NUMBER(6),
	PREZZO FLOAT NOT NULL,
	DURATA INTERVAL DAY TO SECOND,      -- CHIEDERE
	POSTI NUMBER(1) NOT NULL,
	POSTI_DISPONIBILI NUMBER(1) NOT NULL,
	AUTISTA NUMBER(6) NOT NULL,
	PARTENZA TIPO_GPS NOT NULL,
	DATA_PARTENZA DATE NOT NULL,
	ARRIVO TIPO_GPS NOT NULL,
	DATA_ARRIVO DATE,
	STATO VARCHAR2(20) DEFAULT 'Disponibile' CHECK (STATO = 'Disponibile' or STATO = 'Non disponibile'),
	BAGAGLIO VARCHAR2(2) DEFAULT 'No' CHECK (STATO = 'Si' or STATO = 'No'),
	ANIMALI VARCHAR2(2) DEFAULT 'No' CHECK (STATO = 'Si' or STATO = 'No'),
	CONSTRAINT PK_VIAGGI PRIMARY KEY (CODICE)
)
STORAGE (INITIAL 17000 K);

CREATE TABLE LUOGHI (
	GPS TIPO_GPS,
	CITTA NUMBER(5),
	CONSTRAINT PK_LUOGHI PRIMARY KEY (GPS)
)
STORAGE (INITIAL 3200 K);

CREATE TABLE CITTA (        -- CREATA
	NOME VARCHAR2(30) NOT NULL,
	CAP NUMBER(5),
	PROVINCIA CHAR(2) NOT NULL,
	CONSTRAINT PK_CITTA PRIMARY KEY (CAP)
)
STORAGE (INITIAL 292 K);

CREATE TABLE TAPPE (
	VIAGGIO NUMBER(6),
	LUOGO TIPO_GPS,
	CONSTRAINT PK_TAPPE PRIMARY KEY (VIAGGIO, LUOGO)
)
STORAGE (INITIAL 14700 K);