-- DBA_PROGETTO in Dba_Progetto
-- CREAZIONE VINCOLI DI INTEGRITA'
ALTER TABLE AUTISTI ADD CONSTRAINT FK_AUTISTI1 FOREIGN KEY (UTENTE) REFERENCES UTENTI (ID);
ALTER TABLE AUTISTI ADD CONSTRAINT FK_AUTISTI2 FOREIGN KEY (TARGA_AUTO) REFERENCES AUTO (TARGA);

ALTER TABLE PASSEGGERI ADD CONSTRAINT FK_PASSEGGERI FOREIGN KEY (UTENTE) REFERENCES UTENTI (ID);

ALTER TABLE RECENSIONI ADD CONSTRAINT FK_RECENSIONI1 FOREIGN KEY (RECENSENTE) REFERENCES UTENTI (ID);
ALTER TABLE RECENSIONI ADD CONSTRAINT FK_RECENSIONI2 FOREIGN KEY (RECENSITO) REFERENCES UTENTI (ID);
ALTER TABLE RECENSIONI ADD CONSTRAINT FK_RECENSIONI3 FOREIGN KEY (VIAGGIO) REFERENCES VIAGGI (CODICE);

ALTER TABLE PRENOTAZIONI ADD CONSTRAINT FK_PRENOTAZIONI1 FOREIGN KEY (PASSEGGERO) REFERENCES UTENTI (ID);
ALTER TABLE PRENOTAZIONI ADD CONSTRAINT FK_PRENOTAZIONI2 FOREIGN KEY (VIAGGIO) REFERENCES VIAGGI (CODICE);

ALTER TABLE VIAGGI ADD CONSTRAINT FK_VIAGGI1 FOREIGN KEY (AUTISTA) REFERENCES AUTISTI (UTENTE);
ALTER TABLE VIAGGI ADD CONSTRAINT FK_VIAGGI2 FOREIGN KEY (PARTENZA) REFERENCES LUOGHI (GPS);
ALTER TABLE VIAGGI ADD CONSTRAINT FK_VIAGGI3 FOREIGN KEY (ARRIVO) REFERENCES LUOGHI (GPS);

ALTER TABLE LUOGHI ADD CONSTRAINT FK_LUOGHI FOREIGN KEY (CITTA) REFERENCES CITTA (CAP);

ALTER TABLE TAPPE ADD CONSTRAINT FK_TAPPE1 FOREIGN KEY (VIAGGIO) REFERENCES VIAGGI (CODICE);
ALTER TABLE TAPPE ADD CONSTRAINT FK_TAPPE2 FOREIGN KEY (LUOGO) REFERENCES LUOGHI (GPS);