CREATE OR REPLACE VIEW LISTA_VIAGGI_ARRIVI_PARTENZE AS
SELECT V.CODICE AS CODICE_VIAGGIO, C1.NOME AS CITTA_DI_PARTENZA, C2.NOME AS CITTA_DI_ARRIVO FROM VIAGGI V, LUOGHI L1, CITTA C1, LUOGHI L2, CITTA C2
WHERE V.LATITUDINE_PARTENZA = L1.LATITUDINE AND V.LONGITUDINE_PARTENZA = L1.LONGITUDINE AND L1.CITTA = C1.CODICE
AND V.LATITUDINE_ARRIVO = L2.LATITUDINE AND V.LONGITUDINE_ARRIVO = L2.LONGITUDINE AND L2.CITTA = C2.CODICE
ORDER BY CODICE_VIAGGIO;

CREATE OR REPLACE VIEW LISTA_VIAGGI_AUTISTI AS
SELECT V.CODICE AS CODICE_VIAGGIO, U.NOME AS NOME_AUTISTA, U.COGNOME AS COGNOME_AUTISTA
FROM VIAGGI V, UTENTI U WHERE V.AUTISTA = U.ID
ORDER BY CODICE_VIAGGIO;

CREATE OR REPLACE VIEW LISTA_RECENSIONI_AUTISTI AS
SELECT U.USERNAME AS AUTISTA, R.VOTO AS VOTO, R.GIUDIZIO AS GIUDIZIO
FROM RECENSIONI R, AUTISTI A, UTENTI U
WHERE  A.UTENTE = U.ID AND R.RECENSITO = U.ID 
ORDER BY AUTISTA, VOTO DESC;

CREATE OR REPLACE VIEW LISTA_RECENSIONI_PASSEGGERI AS
SELECT U.USERNAME AS PASSEGGERO, R.VOTO AS VOTO, R.GIUDIZIO AS GIUDIZIO
FROM RECENSIONI R, PASSEGGERI P, UTENTI U
WHERE  P.UTENTE = U.ID AND R.RECENSITO = U.ID
ORDER BY PASSEGGERO, VOTO DESC;

CREATE OR REPLACE VIEW MEDIA_VOTI_AUTISTI AS
SELECT U.USERNAME AS AUTISTA, AVG(R.VOTO) AS MEDIA_VOTO
FROM UTENTI U, AUTISTI A, RECENSIONI R
WHERE A.UTENTE = U.ID AND R.RECENSITO = U.ID
GROUP BY U.ID, U.USERNAME ORDER BY AUTISTA;

CREATE OR REPLACE VIEW AUTISTI_MIGLIORI AS
SELECT M.AUTISTA AS AUTISTA, M.MEDIA_VOTO AS MEDIA_VOTO
FROM MEDIA_VOTI_AUTISTI M
WHERE MEDIA_VOTO >= 4
ORDER BY M.AUTISTA;

CREATE OR REPLACE VIEW NUM_VIAGGI_AUTISTI AS
SELECT U.USERNAME AS AUTISTA, COUNT (U.ID) AS NUMERO_VIAGGI
FROM UTENTI U, AUTISTI A, VIAGGI V
WHERE V.AUTISTA = U.ID AND A.UTENTE = U.ID
GROUP BY U.ID, U.USERNAME ORDER BY U.ID;

CREATE OR REPLACE VIEW NUM_VIAGGI_PASSEGGERI AS
SELECT U.USERNAME AS PASSEGGERO, COUNT(U.ID) AS NUMERO_VIAGGI
FROM UTENTI U, PRENOTAZIONI P 
WHERE P.PASSEGGERO = U.ID AND P.STATO = 'Accettata'
GROUP BY U.ID, U.USERNAME ORDER BY U.ID;

CREATE OR REPLACE VIEW PASSEGGERI_VIAGGI AS
SELECT V.CODICE AS CODICE_VIAGGIO, U1.USERNAME AS USER_AUTISTA, U2.USERNAME AS USER_PASSEGGERO
FROM PRENOTAZIONI PR, VIAGGI V, UTENTI U1, UTENTI U2
WHERE V.CODICE=PR.VIAGGIO AND PR.PASSEGGERO=U2.ID AND V.AUTISTA=U1.ID AND PR.STATO = 'Accettata'
GROUP BY V.CODICE, V.AUTISTA, U1.USERNAME, U2.USERNAME ORDER BY CODICE_VIAGGIO;

CREATE OR REPLACE VIEW CITTA_MAX_PARTENZE AS
SELECT C1.NOME AS CITTA_PARTENZA
FROM VIAGGI V1, LUOGHI L1,CITTA C1
WHERE V1.LATITUDINE_PARTENZA = L1.LATITUDINE AND V1.LONGITUDINE_PARTENZA = L1.LONGITUDINE AND L1.CITTA = C1.CODICE
GROUP BY C1.NOME
HAVING COUNT(*)>= ALL(
SELECT COUNT(*)
FROM VIAGGI V, LUOGHI L, CITTA C
WHERE V.LATITUDINE_PARTENZA = L.LATITUDINE AND V.LONGITUDINE_PARTENZA = L.LONGITUDINE AND L.CITTA = C.CODICE
GROUP BY C.NOME
);

CREATE OR REPLACE VIEW CITTA_MAX_ARRIVI AS
SELECT C1.NOME AS CITTA_DESTINAZIONE
FROM VIAGGI V1, LUOGHI L1,CITTA C1
WHERE V1.LATITUDINE_ARRIVO = L1.LATITUDINE AND V1.LONGITUDINE_ARRIVO = L1.LONGITUDINE AND L1.CITTA = C1.CODICE
GROUP BY C1.NOME
HAVING COUNT(*)>= ALL(
SELECT COUNT(*)
FROM VIAGGI V, LUOGHI L, CITTA C
WHERE V.LATITUDINE_ARRIVO = L.LATITUDINE AND V.LONGITUDINE_ARRIVO = L.LONGITUDINE AND L.CITTA=C.CODICE
GROUP BY C.NOME
);